/* File produced with PSPTEX Gimp plugin v1.05
   Written by Franck Charlet. */

#define CONTROLS1_1_TEXTURE_WIDTH 512
#define CONTROLS1_1_TEXTURE_REAL_WIDTH 512
#define CONTROLS1_1_TEXTURE_HEIGHT 512
#define CONTROLS1_1_TEXTURE_REAL_HEIGHT 512
#define CONTROLS1_1_TEXTURE_FORMAT 3
#define CONTROLS1_1_TEXTURE_MIPMAPS 0
#define CONTROLS1_1_TEXTURE_SWIZZLE 1
#define CONTROLS1_1_MIPMAPS_OFFSET0 0
