/* File produced with PSPTEX Gimp plugin v1.05
   Written by Franck Charlet. */

#define SEBONPSP2_TEXTURE_WIDTH 128
#define SEBONPSP2_TEXTURE_REAL_WIDTH 128
#define SEBONPSP2_TEXTURE_HEIGHT 256
#define SEBONPSP2_TEXTURE_REAL_HEIGHT 143
#define SEBONPSP2_TEXTURE_FORMAT 3
#define SEBONPSP2_TEXTURE_MIPMAPS 0
#define SEBONPSP2_TEXTURE_SWIZZLE 1
#define SEBONPSP2_MIPMAPS_OFFSET0 0
